name: Build GDrive CLI

on:
  push:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.19
      uses: actions/setup-go@v2
      with:
        go-version: 1.19
      id: go

    - name: Check out repository
      uses: actions/checkout@v2

    - name: Get https://github.com/msfjarvis/gdrive code
      run: |
        export GOPATH=$HOME/go
        export GOBIN=$(go env GOPATH)/bin
        export PATH=$PATH:$GOPATH
        export PATH=$PATH:$GOBIN
        mkdir -p $GOPATH/pkg
        mkdir -p $GOBIN
        git clone https://github.com/msfjarvis/gdrive.git $HOME/go/src/github.com/msfjarvis/gdrive
    - name: Build
      run: |
        cp -r build/* $HOME/go/src/github.com/msfjarvis/gdrive/
        cd $HOME/go/src/github.com/msfjarvis/gdrive/
        chmod +x build-selected.sh
        chmod +x build.sh
        ./build-selected.sh
        ls -al _release/bin

    - name: Copy release file
      run: |
        mkdir release
        cp -r $HOME/go/src/github.com/msfjarvis/gdrive/_release/bin/* release
        
    - name: Zip result
      uses: vimtor/action-zip@v1
      with:
          files: release/
          dest: gdrive.zip
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: gdrive.zip
        asset_name: gdrive.zip
        tag: latest
        overwrite: true
        body: "release"
